
export const SIGN_UP_SUCCESS = "SIGNED_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGNED_UP_ERROR";
export const SIGN_IN_SUCCESS = "SIGNED_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGNED_IN_ERROR";
export const SIGN_OUT_SUCCESS = "SIGNED_OUT_SUCCESS";

export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_ERROR = "GET_ALL_EVENTS_ERROR";
export const GET_EVENT_DETAILS_SUCCESS = "GET_EVENT_DETAILS_SUCCESS";
export const GET_EVENT_DETAILS_ERROR = "GET_EVENT_DETAILS_ERROR";
export const GET_MY_EVENTS_SUCCESS = "GET_MY_EVENTS_SUCCESS";
export const GET_MY_EVENTS_ERROR = "GET_MY_EVENTS_ERROR";
export const ADD_EVENT_ERROR = "ADD_EVENT_ERROR";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";

export const SEND_INVITE_SUCCESS = "SEND_INVITE_SUCCESS";
export const SEND_INVITE_ERROR = "SEND_INVITE_ERROR";